import type { StyleSpecification } from 'maplibre-gl';

export const darkDramaticStyle: StyleSpecification = {
  version: 8,
  name: 'Dark Dramatic',
  glyphs: 'https://tiles.openfreemap.org/font/{fontstack}/{range}.pbf',
  sources: {
    openmaptiles: {
      type: 'vector',
      url: 'https://tiles.openfreemap.org/planet',
    },
  },
  layers: [
    // ── Background ──────────────────────────────────────────────────────────
    {
      id: 'background',
      type: 'background',
      paint: { 'background-color': '#07080f' },
    },

    // ── Water ───────────────────────────────────────────────────────────────
    {
      id: 'water',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'water',
      paint: { 'fill-color': '#0c1828', 'fill-antialias': true },
    },
    {
      id: 'waterway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'waterway',
      filter: ['==', '$type', 'LineString'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#111f35',
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 0.5, 12, 1.5, 16, 3],
      },
    },

    // ── Landcover ───────────────────────────────────────────────────────────
    {
      id: 'landcover-wood',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['in', ['get', 'class'], ['literal', ['wood', 'forest']]],
      paint: { 'fill-color': '#0a1210', 'fill-opacity': 0.9 },
    },
    {
      id: 'landcover-grass',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['in', ['get', 'class'], ['literal', ['grass', 'meadow', 'scrub', 'heath']]],
      paint: { 'fill-color': '#0c1310', 'fill-opacity': 0.85 },
    },
    {
      id: 'landcover-sand',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['in', ['get', 'class'], ['literal', ['sand', 'beach']]],
      paint: { 'fill-color': '#1a1810', 'fill-opacity': 0.75 },
    },
    {
      id: 'landcover-wetland',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landcover',
      filter: ['in', ['get', 'class'], ['literal', ['wetland', 'wetland_noveg']]],
      paint: { 'fill-color': '#0d1a20', 'fill-opacity': 0.75 },
    },

    // ── Landuse ─────────────────────────────────────────────────────────────
    {
      id: 'landuse-residential',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['in', ['get', 'class'], ['literal', ['residential', 'suburb', 'neighbourhood']]],
      paint: { 'fill-color': '#0d0d15', 'fill-opacity': 0.7 },
    },
    {
      id: 'landuse-commercial',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['in', ['get', 'class'], ['literal', ['commercial', 'retail']]],
      paint: { 'fill-color': '#0f0f18', 'fill-opacity': 0.65 },
    },
    {
      id: 'landuse-industrial',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', ['get', 'class'], 'industrial'],
      paint: { 'fill-color': '#0e0f0d', 'fill-opacity': 0.7 },
    },
    {
      id: 'landuse-park',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: [
        'in',
        ['get', 'class'],
        ['literal', ['park', 'garden', 'pitch', 'grass', 'recreation_ground', 'village_green']],
      ],
      paint: { 'fill-color': '#0c1510', 'fill-opacity': 0.9 },
    },
    {
      id: 'landuse-cemetery',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'landuse',
      filter: ['==', ['get', 'class'], 'cemetery'],
      paint: { 'fill-color': '#0e1310', 'fill-opacity': 0.8 },
    },

    // ── Aeroways ────────────────────────────────────────────────────────────
    {
      id: 'aeroway-fill',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      filter: ['==', '$type', 'Polygon'],
      paint: { 'fill-color': '#131320', 'fill-opacity': 0.9 },
    },
    {
      id: 'aeroway-runway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'aeroway',
      filter: ['in', ['get', 'class'], ['literal', ['runway', 'taxiway']]],
      paint: {
        'line-color': '#2a2840',
        'line-width': ['interpolate', ['linear'], ['zoom'], 10, 1, 14, 5],
      },
    },

    // ── Roads — casing ──────────────────────────────────────────────────────
    {
      id: 'road-motorway-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'motorway'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#0e0e1c',
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 2.5, 12, 6, 16, 16],
        'line-opacity': 0.9,
      },
    },
    {
      id: 'road-trunk-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'trunk'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#0c0c18',
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 2, 12, 5, 16, 13],
        'line-opacity': 0.8,
      },
    },
    {
      id: 'road-primary-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'primary'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#0a0a14',
        'line-width': ['interpolate', ['linear'], ['zoom'], 9, 1.5, 12, 4, 16, 11],
        'line-opacity': 0.7,
      },
    },
    {
      id: 'road-secondary-casing',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', ['get', 'class'], ['literal', ['secondary', 'tertiary']]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#090910',
        'line-width': ['interpolate', ['linear'], ['zoom'], 11, 1, 14, 3, 16, 8],
        'line-opacity': 0.6,
      },
    },

    // ── Roads — fill ────────────────────────────────────────────────────────
    // Cool neutral white-gray hierarchy — distinct from all building era colors
    {
      id: 'road-minor',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: [
        'in',
        ['get', 'class'],
        ['literal', ['minor', 'service', 'residential', 'unclassified', 'track']],
      ],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#1e1e2e',
        'line-width': ['interpolate', ['linear'], ['zoom'], 13, 0.3, 15, 1, 17, 3],
      },
    },
    {
      id: 'road-path',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', ['get', 'class'], ['literal', ['path', 'footway', 'steps', 'cycleway']]],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#1a1a28',
        'line-width': ['interpolate', ['linear'], ['zoom'], 14, 0.3, 17, 1.5],
        'line-dasharray': [2, 2],
      },
    },
    {
      id: 'road-tertiary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'tertiary'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#32323e',
        'line-width': ['interpolate', ['linear'], ['zoom'], 11, 0.4, 14, 1.5, 16, 5],
      },
    },
    {
      id: 'road-secondary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'secondary'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#50505e',
        'line-width': ['interpolate', ['linear'], ['zoom'], 10, 0.5, 13, 2, 16, 6],
      },
    },
    {
      id: 'road-primary',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'primary'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#3a3a42',
        'line-width': ['interpolate', ['linear'], ['zoom'], 9, 0.6, 12, 2.5, 16, 8],
      },
    },
    {
      id: 'road-trunk',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'trunk'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#40404b',
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 0.9, 12, 3, 16, 10],
      },
    },
    {
      id: 'road-motorway',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['==', ['get', 'class'], 'motorway'],
      layout: { 'line-cap': 'round', 'line-join': 'round' },
      paint: {
        'line-color': '#e0e0f0',
        'line-width': ['interpolate', ['linear'], ['zoom'], 8, 1.5, 12, 4, 16, 12],
      },
    },
    {
      id: 'rail',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'transportation',
      filter: ['in', ['get', 'class'], ['literal', ['rail', 'transit', 'subway', 'light_rail']]],
      layout: { 'line-cap': 'butt', 'line-join': 'miter' },
      paint: {
        'line-color': '#2d2545',
        'line-width': ['interpolate', ['linear'], ['zoom'], 10, 0.4, 14, 1.5],
        'line-dasharray': [4, 4],
      },
    },

    // ── Basemap Buildings (subtle, for context at city-wide zoom) ───────────
    {
      id: 'building-basemap',
      type: 'fill',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 13,
      paint: {
        'fill-color': '#1a1a28',
        'fill-opacity': ['interpolate', ['linear'], ['zoom'], 13, 0.2, 15, 0.55],
        'fill-antialias': true,
      },
    },
    {
      id: 'building-basemap-outline',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'building',
      minzoom: 14,
      paint: { 'line-color': '#252538', 'line-width': 0.4, 'line-opacity': 0.5 },
    },

    // ── Boundaries ──────────────────────────────────────────────────────────
    {
      id: 'boundary-state',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['==', ['get', 'admin_level'], 4],
      paint: {
        'line-color': '#3a2858',
        'line-width': 0.8,
        'line-dasharray': [5, 4],
        'line-opacity': 0.65,
      },
    },
    {
      id: 'boundary-country',
      type: 'line',
      source: 'openmaptiles',
      'source-layer': 'boundary',
      filter: ['==', ['get', 'admin_level'], 2],
      layout: { 'line-join': 'round' },
      paint: {
        'line-color': '#5a4082',
        'line-width': ['interpolate', ['linear'], ['zoom'], 3, 0.7, 7, 1.8, 10, 2.8],
        'line-opacity': 0.85,
      },
    },

    // ── Labels — Water ───────────────────────────────────────────────────────
    {
      id: 'water-name',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'water_name',
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Italic'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 10, 14, 14],
        'text-max-width': 6,
        'symbol-placement': 'line',
      },
      paint: {
        'text-color': '#2a5a9a',
        'text-halo-color': '#07080f',
        'text-halo-width': 1.5,
      },
    },

    // ── Labels — Roads ───────────────────────────────────────────────────────
    {
      id: 'road-label-secondary',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      filter: ['in', ['get', 'class'], ['literal', ['secondary', 'tertiary']]],
      minzoom: 14,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': 9,
        'symbol-placement': 'line',
        'text-max-angle': 30,
      },
      paint: {
        'text-color': '#5a5060',
        'text-halo-color': '#07080f',
        'text-halo-width': 1,
      },
    },
    {
      id: 'road-label-primary',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      filter: ['in', ['get', 'class'], ['literal', ['primary', 'trunk']]],
      minzoom: 12,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': 10,
        'symbol-placement': 'line',
        'text-max-angle': 30,
      },
      paint: {
        'text-color': '#3a3a42',
        'text-halo-color': '#07080f',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'road-label-motorway',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'transportation_name',
      filter: ['==', ['get', 'class'], 'motorway'],
      minzoom: 10,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Bold'],
        'text-size': 11,
        'symbol-placement': 'line',
        'text-max-angle': 30,
      },
      paint: {
        'text-color': '#d0d0e0',
        'text-halo-color': '#07080f',
        'text-halo-width': 1.5,
      },
    },

    // ── Labels — Places ──────────────────────────────────────────────────────
    {
      id: 'place-neighbourhood',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['in', ['get', 'class'], ['literal', ['neighbourhood', 'hamlet', 'suburb']]],
      minzoom: 13,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': 9,
        'text-max-width': 6,
        'text-transform': 'uppercase',
        'text-letter-spacing': 0.1,
      },
      paint: {
        'text-color': '#6a6a78',
        'text-halo-color': '#07080f',
        'text-halo-width': 1,
      },
    },
    {
      id: 'place-village',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'village'],
      minzoom: 10,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 10, 10, 14, 13],
        'text-max-width': 7,
      },
      paint: {
        'text-color': '#888898',
        'text-halo-color': '#07080f',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'place-town',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'town'],
      minzoom: 8,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 8, 11, 12, 15],
        'text-max-width': 8,
      },
      paint: {
        'text-color': '#a0a0b8',
        'text-halo-color': '#07080f',
        'text-halo-width': 1.5,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'place-city',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'city'],
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 5, 11, 9, 17, 14, 22],
        'text-max-width': 9,
        'text-anchor': 'center',
        'icon-allow-overlap': false,
      },
      paint: {
        'text-color': '#c0c0d8',
        'text-halo-color': '#07080f',
        'text-halo-width': 2,
        'text-halo-blur': 0.5,
      },
    },
    {
      id: 'place-state',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'state'],
      maxzoom: 8,
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Regular'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 4, 9, 8, 14],
        'text-max-width': 8,
        'text-transform': 'uppercase',
        'text-letter-spacing': 0.12,
      },
      paint: {
        'text-color': '#7878a0',
        'text-halo-color': '#07080f',
        'text-halo-width': 1.5,
      },
    },
    {
      id: 'place-country',
      type: 'symbol',
      source: 'openmaptiles',
      'source-layer': 'place',
      filter: ['==', ['get', 'class'], 'country'],
      layout: {
        'text-field': ['coalesce', ['get', 'name_en'], ['get', 'name']],
        'text-font': ['Noto Sans Bold'],
        'text-size': ['interpolate', ['linear'], ['zoom'], 3, 9, 7, 20, 10, 24],
        'text-max-width': 9,
        'text-transform': 'uppercase',
        'text-letter-spacing': 0.15,
      },
      paint: {
        'text-color': '#d8d8f0',
        'text-halo-color': '#07080f',
        'text-halo-width': 2,
        'text-halo-blur': 1,
        'text-opacity': ['interpolate', ['linear'], ['zoom'], 2, 0.6, 5, 1],
      },
    },
  ],
};
