/**
 * Total walking distance of each tour, in metres.
 *
 * GENERATED by scripts/build-tour-routes.mjs alongside the route geometry.
 * Kept apart from tourRoutes.ts so the home page can show a tour's length
 * without loading every coordinate.
 */

export const TOUR_DISTANCES: Record<string, number> = {
  "nurzhol": 6662,
  "tselinograd": 6446,
  "sacred": 21048,
  "expo": 7324
};

/** "11.8 km" — or "750 m" for anything under a kilometre. */
export function formatTourDistance(tourId: string): string | null {
  const metres = TOUR_DISTANCES[tourId];
  if (metres == null) return null;
  return metres < 1000 ? `${metres} m` : `${(metres / 1000).toFixed(1)} km`;
}
